accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.shortcuts import redirect
from . import views

urlpatterns = [
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^login/$', auth_views.login, name='login',
        kwargs={
            'template_name': 'accounts/login_form.html'}),
    url(r'^logout/$', auth_views.logout, name='logout',
        kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^signup/$', views.signup, name='signup'),
]

app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.rest_index, name='rest_index'),
    url(r'^new/$', views.rest_new, name='rest_new'),
    url(r'^list/$', views.rest_list, name='rest_list'),
    url(r'^(?P<id>\d+)/edit/$', views.rest_edit, name='rest_edit'),
    url(r'^(?P<id>\d+)/delete/$', views.rest_delete, name='rest_delete'),
]

restaurant/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    url(r'^$', lambda r: redirect('app:rest_index'),name='root'), #url 유도
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls',namespace='app')),
    url(r'^accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#어드민에서 사진 보기, 미디어 파일 서빙시키기

accounts/models.py
from django.db import models


from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)

app/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail



class Restaurant(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    restimage = ProcessedImageField(blank=True,
            processors=[Thumbnail(350, 350)],
            upload_to='app/restimage/%Y/%m/%d',
            format='JPEG',
            options={'quality': 80})
    restname = models.CharField(max_length=50)
    restsite = models.CharField(max_length=200)

    def __str__(self):
        return self.restname

    def get_absolute_url(self):
        return reverse('app:rest_index')

accounts/forms.py
import unicodedata

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from .models import Profile
from . import views
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

class UsernameField(forms.CharField):
    def to_python(self, value):
        return unicodedata.normalize('NFKC', super(UsernameField, self).to_python(value))

class SignupForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("두개의 암호 필드가 일치하지 않네요!"),
    }
    password1 = forms.CharField(
        label=_("패스워드"),
        strip=False,
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label=_("패스워드 확인"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("이전과 동일한 패스워드를 입력하세요!"),
    )

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update({'autofocus': ''})

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

app/forms.py
from django import forms
from .models import Restaurant

class RestForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ('restimage','restname','restsite',)

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import SignupForm
from django.contrib.auth.decorators import login_required
# from app.forms import *

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, '회원가입 했습니다.')
            return redirect(settings.LOGIN_URL)


    else:
        form = SignupForm()
    return render(request, 'accounts/signup_form.html',{
        'form':form,
    })

@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from .models import Restaurant
from .forms import RestForm

def rest_list(request):
    qs = Restaurant.objects.all()

    q = request.GET.get('q', '')

    if q:
        qs = qs.filter(restname__icontains=q)

    return render(request, 'app/rest_list.html',{
        'rest_list':qs
    })

def rest_index(request):
    restaurant = Restaurant.objects.order_by('?').first()
    return render(request, 'app/rest_index.html',{
        'restaurant':restaurant
    })


@login_required
def rest_new(request):
    if request.method == 'POST':
        form = RestForm(request.POST, request.FILES)
        if form.is_valid():
            restaurant = form.save(commit=False)
            restaurant.author = request.user
            restaurant.save()
            messages.success(request, '식당이 랜덤리스트에 들어갔습니다.')
            #메세지 프레임워크
            return redirect(restaurant)
    else:
        form = RestForm()
    return render(request, 'app/rest_new.html',{
        'form': form
    })

@login_required
def rest_edit(request, id):
    restaurant = get_object_or_404(Restaurant, id=id)
    if restaurant.author != request.user:
        return redirect(restaurant)
    if request.method == 'POST':
        form = RestForm(request.POST, request.FILES, instance=restaurant)
        if form.is_valid():
            restaurant = form.save(commit=False)
            restaurant.author = request.user
            restaurant.save()
            messages.success(request, '식당 정보를 수정했습니다.')
            #메세지 프레임워크
            return redirect(restaurant)
    else:
        form = RestForm(instance=restaurant)
    return render(request, 'app/rest_new.html',{
        'form': form
    })


@login_required
def rest_delete(request,id):
    restaurant = Restaurant.objects.get(id=id)
    if restaurant.author != request.user:
        return redirect(restaurant)
    restaurant.delete()
    messages.success(request, '식당을 삭제했습니다.')
    return redirect(restaurant)

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html" %}

{% block content %}
<form action="" method="post" class="form-horizontal">
<legend>로그인</legend>
{% csrf_token %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">

        <div class="form-group">
        <label for="id_username">아이디:</label>
          <div class="col-sm-10">
            <input autofocus="" id="id_username" maxlength="254" name="username" type="text" required="">

            <p class="help-block"></p>
          </div>


        </div>
        <div class="form-group">
        <label for="id_password">패스워드:</label>
          <div class="col-sm-10">
            <input id="id_password" name="password" type="password" required="">
            <p class="help-block"></p>
          </div>
        </div>
        {% if form.errors %}
        <p>사용자 아이디와 패스워드가 일치하지 않습니다. 다시 시도해주세요.</p>
        {% endif %}

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <p><button type="submit" class="btn btn-info btn-block">확인</button></p>
        </div>
      </div>


    </div>
  </div>
</div>
</form>
<script>
$(function() {
  $('.form-group label').addClass('col-sm-2');
  $('.form-group input, .form-group textarea').addClass('form-control');
  });
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <p style="text-align:center;"></p>
  <h2>{{ user }}님의 프로필!</h2>
  <ul>

      <li>아이디 : {{user.username}}</li>
      <li>가입날짜 : {{user.date_joined}}</li>

  </ul>


    </div>
  </div>
</div>
  {% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}


{% block content %}
<form action="" method="post">
<legend>회원가입!</legend>
{% csrf_token %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">

  {{ form.as_p }}

  <div class="form-group">
    <div class="col-sm-12">
      <button type="submit" class="btn btn-info btn-block">회원가입</button>
    </div>
  </div>
      </div>
    </div>
  </div>
</div>

</form>
<script>
$(function() {
  $('.form-group label').addClass('col-sm-2');
  $('.form-group input, .form-group textarea').addClass('form-control');
});


</script>

{% endblock %}

app/templates/app/layout.html
{% extends "layout.html" %}

app/templates/app/rest_index.html
{% extends "app/layout.html" %}
{% load imagekit %}

{% block content %}

{% if restaurant %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <p style="text-align:center;"></p>
          <p style="float: right"><small>작성자 : {{ restaurant.author }}</small></p>

          <div>
            <p>식당 이름! : {{ restaurant.restname }}</p>
          </div>
          {% if restaurant.restimage %}

            {% thumbnail "350x350" restaurant.restimage as thumb %}

            <center><img src="{{ thumb.url }}"
              width="{{ thumb.width }}" height="{{ thumb.height }}"
              alt="Cinque Terre"
              class="img-responsive img-rounded"
              style="max_length: 100%;"/></center>
          {% else %}
            <center>이미지가 없네요! 업로드 해주세요!</center>
          {% endif %}
          {% if not restaurant.restimage %}
          <center>
             <img src="http://upload2.inven.co.kr/upload/2016/01/03/bbs/i13737846850.gif" width="350px" height="250px"/>
          </center>
          {% endif %}
          <p>간략한 위치 : {{ restaurant.restsite }}</p>
        </hr>

          <form><input type="button" class="btn btn-primary btn-block" value="다른 식당 검색!" onClick="window.location.reload()"></form>
      </div>
    </div>
  </div>
{% endif %}

{% endblock %}

app/templates/app/rest_list.html
{% extends "app/layout.html" %}

{% block content %}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

<div class="container">
	<div class="row">


        <div class="col-md-12">
        <h4>내 식당 목록</h4>
        <div class="table-responsive">


              <table id="mytable" class="table table-bordred table-striped">

                   <thead>

                   <!-- <th><input type="checkbox" id="checkall" /></th> -->
                   <th>식당 이름</th>
                    <th>식당 위치</th>
                     <th>작성자</th>
											<th>수정</th>
                       <th>삭제</th>
                   </thead>
    <tbody>
    {% for rest in rest_list %}
      {% if rest.author == request.user %}
    <tr>
    <!-- <td><input type="checkbox" class="checkthis" /></td> -->
    <td>{{ rest.restname }}</td>
    <td>{{ rest.restsite }}</td>
    <td>{{ rest.author }}</td>
		<td><a id="rest_edit" href="{% url "app:rest_edit" rest.id %}">
			<p data-placement="top" data-toggle="tooltip" title="Edit">
			<button class="btn btn-primary btn-xs" data-title="Edit" >
				<span class="glyphicon glyphicon-pencil"></span></button></p></a></td>

    <td><a id="delete_rest" href="{% url "app:rest_delete" rest.id %}">
      <p data-placement="top" data-toggle="tooltip" title="Delete">
      <button class="btn btn-danger btn-xs" data-title="Delete" >
        <span class="glyphicon glyphicon-trash"></span></button></p></a></td>
    </tr>
      {% endif %}
    {% endfor %}

    </tbody>

</table>

<!-- <div class="clearfix"></div>
<ul class="pagination pull-right" id=mypager>
  <li class="disabled"><a href="#"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
  <li class="active"><a href="#">1</a></li>
  <li><a href="#">2</a></li>
  <li><a href="#">3</a></li>
  <li><a href="#">4</a></li>
  <li><a href="#">5</a></li>
  <li><a href="#"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
</ul> -->

            </div>

        </div>
	</div>
</div>
<!-- <script>
$(document).ready(function(){
$("#mytable #checkall").click(function () {
        if ($("#mytable #checkall").is(':checked')) {
            $("#mytable input[type=checkbox]").each(function () {
                $(this).prop("checked", true);
            });

        } else {
            $("#mytable input[type=checkbox]").each(function () {
                $(this).prop("checked", false);
            });
        }
    });
});
</script> -->



{% endblock %}

app/templates/app/rest_new.html
{% extends "app/layout.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
  <h2>식당 추가,수정!</h2>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.restimage.id_for_label }}" class="control-label col-sm-2">식당 이미지</label>
          <div class="col-sm-10">
          <a data-toggle="tooltip" title="350x350크기로 고정해서 올라갑니다. 가급적 JPEG로 해주세요. 꼭 올릴 필요는 없습니다!">{{ form.restimage }}</a>
          </div>
      </div>
      <div class="form-group">
        <label for="{{ form.restname.id_for_label }}" class="control-label col-sm-2">식당 이름</label>
          <div class="col-sm-10">
          <a data-toggle="tooltip" title="식당 이름 필수입니다!">{{ form.restname }}</a>
          </div>
      </div>
      <div class="form-group">
        <label for="{{ form.restsite.id_for_label }}" class="control-label col-sm-2">식당 위치</label>
          <div class="col-sm-10">
          <a data-toggle="tooltip" title="간략한 주소 부탁드립니다">{{ form.restsite }}</a>
          </div>
      </div>
      <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">확인</button>
        <a href="{% url "app:rest_list" %}"><button type="button" class="btn btn-info">이전 목록</button></a>
      </div>
      </div>
    </form>
</div>
</div>
</div>

<script>
$(function() {
  $('.form-group label').addClass('col-sm-2');
  $('.form-group input, .form-group textarea').addClass('form-control');
  });
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}

restaurant/templates/layout.html
<!doctype html>
{% load staticfiles %}
{% load imagekit %}
<html>
  <head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css">
  <!-- Include meta tag to ensure proper rendering and touch zooming -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



  <title>랜덤 식당</title>

  </head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "root" %}">랜덤 식당</a>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav">
{% if user.is_authenticated %}
        <li><a href="{% url "app:rest_new" %}">식당 추가!</a></li>
        <li><a href="{% url "app:rest_list" %}">내 식당 목록!</a></li>
        {% if restaurant.author == user %}
          <!-- <li><a href="{% url "app:rest_edit" restaurant.id %}">식당 수정!</a></li> -->
          <!-- <li><a href="{% url "app:rest_delete" restaurant.id %}">식당 삭제</a></li> -->
        {% endif %}

{% endif %}

    {% if not user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url "signup" %}?next={% url "login" %}"
                 data-toggle="tooltip" title="회원가입시 식당 추가,수정 가능!">
          <span class="glyphicon glyphicon-user"></span>회원가입</a></li>
          <li><a href="{% url "login" %}?next={% url "root" %}">
          <span class="glyphicon glyphicon-log-in"></span>로그인</a></li>
      </ul>
    {% else %}

        <li><a href="{% url "profile" %}">프로필</a></li>
        <li><a href="{% url "logout" %}?next={{ request.path }}">로그아웃</a></li>
      </ul>
      <!-- ?next={{ request.path }} <- 이걸로 있었던주소로 돌아오기 -->

    {% endif %}
    </div>
  </div>
</div>
</nav>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

  {% if messages %}
  <div class="container">


    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
      {{ message.tags }}
      {{ message.message }}
    {% endfor %}

    </div>
  </div>
  {% endif %}

  {% block content %}
  {% endblock %}
<hr />
</body>
</html>